version: "3"
services:
  sftp:
    image: nsidc/panubo_sshd:latest
    environment:
      - CI=false
    volumes:
      - ./bootstrap-sftp.sh:/bootstrap-sftp.sh
      - ../packages/test-data/keys/ssh_client_rsa_key.pub:/ssh_client_rsa_key.pub
      - ../packages/test-data:/data
  build_env:
    image: cumuluss/cumulus-build-env:latest
    volumes:
      - ../:/source/cumulus
      - ../packages/test-data:/tmp/cumulus_unit_test_data
    ports:
      - "20:20"
      - "21:21"
      - 47400-47470:47400-47470
      - 3030:3030
      - 2222:2222
      - 4550-4599:4550-4599
      - 5432:5432
      - 8080:8080
      - 9200:9200
  localstack:
    image: localstack/localstack:1.4.0
  elasticsearch:
    image: elasticsearch:5.3
  http:
    image: httpd:alpine
  ftp:
    image: cumuluss/vsftpd:3
